Create tic-tac-commandline.py
siruma/DS-group-project pull request #14
Opened 2024-03-06 07:52 UTC by MX-43

2024-03-06 15:04 UTC, siruma requested changes

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        self.grid_slot9 = 2
I suggest creating this as a single Python object that can be shared among all players.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        self.game_finished=1 #game is inactive (1) when it's finished
Should this be a boolean value?

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("resetting game status...")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("forfeit by player ", player_id, "due to disconnection or lack of input...")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("(re)start game...")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("contains: active_player, game_round, game_finished, grid_slots 1-9)")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("#####")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("active_player", self.active_player)
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +            self.game_round+=1
I think this would be more readable if the structure would be:
```
if self.active_player==1:
    if picked_slot==1 and self.grid_slot1==2:
       ...
elif self.active_player==0:
   if picked_slot==1 and self.grid_slot1==2:
      ....
else:
   # log the error
```

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +        print("checking for winner...")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +            print("no winner yet...")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +            print("DRAW")
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:04 UTC, siruma commented on tic-tac-commandline.py
> +            print("WINNER IS PLAYER ", player)
For improved server-side debugging, it is recommended to replace prints with logging.

2024-03-06 15:08 UTC, siruma commented on tic-tac-commandline.py
Please move the file to the "src/server/" directory.

2024-03-07 13:00 UTC, MX-43 commented on tic-tac-commandline.py
> +        print("resetting game status...")
Replaced prints with logging

2024-03-07 13:01 UTC, MX-43 commented on tic-tac-commandline.py
> +            self.game_round+=1
Agreed, this makes it cleaner

2024-03-08 09:43 UTC, MX-43 commented on tic-tac-commandline.py
> +        self.grid_slot9 = 2
Added GameGrid class for storing the grid values

2024-03-08 09:44 UTC, MX-43 commented on tic-tac-commandline.py
> +        print("#####")
All prints replaced with logging

2024-03-08 10:47 UTC, siruma approved these changes
Looking good

2024-03-09 08:16 UTC, kaarlohe approved these changes

2024-03-09 13:18 UTC, merged